### ISSUE TITLE
No font file font "data/DejaVuSans.ttf"

### ISSUE THREAD

**Issue by shileims** [ChenDarYen/Key-Locked-Rank-One-Editing-for-Text-to-Image-Personalization#5]
Hi Author,
    I meet the following error while I run the command based on SD1.5. 
   No sources: "data/DejaVuSans.ttf"
   Thank you!

**Comment by ChenDarYen** [comment]
Hi, you could download the [DejaVuSans.ttf](https://github.com/prawnpdf/prawn/blob/master/data/fonts/DejaVuSans.ttf) to `./data/`.

**Comment by shileims** [comment]
Thank you so much!
